// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_dart/firebase_dart.dart';
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBzKL8zgDPvwBqqTC4GgnvmIq3LFioO2tI',
//     appId: '1:535545675507:web:09036ef05c8dec850b4186',
//     messagingSenderId: '535545675507',
//     projectId: 'crossclip-271415',
//     authDomain: 'crossclip-271415.firebaseapp.com',
//     storageBucket: 'crossclip-271415.appspot.com',
//     measurementId: 'G-7FV669JYZW',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCy245_L42wWmiQVp2eOgoo0SsGytaxzrY',
//     appId: '1:535545675507:android:6c5b50aaffd274b30b4186',
//     messagingSenderId: '535545675507',
//     projectId: 'crossclip-271415',
//     storageBucket: 'crossclip-271415.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCr8hHdzF9ZGzi4pQdr7bRKJqNZZtWKCuQ',
//     appId: '1:535545675507:ios:b6f31239cce5d9a40b4186',
//     messagingSenderId: '535545675507',
//     projectId: 'crossclip-271415',
//     storageBucket: 'crossclip-271415.appspot.com',
//     iosClientId:
//         '535545675507-p90gckfqpsjs743pepjoqu7fmo5dki84.apps.googleusercontent.com',
//     iosBundleId: 'com.example.crossclipV2',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCr8hHdzF9ZGzi4pQdr7bRKJqNZZtWKCuQ',
//     appId: '1:535545675507:ios:b6f31239cce5d9a40b4186',
//     messagingSenderId: '535545675507',
//     projectId: 'crossclip-271415',
//     storageBucket: 'crossclip-271415.appspot.com',
//     iosClientId:
//         '535545675507-p90gckfqpsjs743pepjoqu7fmo5dki84.apps.googleusercontent.com',
//     iosBundleId: 'com.example.crossclipV2',
//   );
// }
